site_name: Pubky Docs

theme:
  name: material
  palette:
    - toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.footer
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.snippets

nav:
  - Intro: index.md
  - Get Started: 01_get_started.md
  - Initialize Client: 02_init_client.md
  - PKDNS: 05_pkdns.md
  - PKDNS TLS: 09_pkdns_tls.md
  - Storage API: 03_storage_api.md
  - Homeserver API:
      - Signup: 04_homeserver_api/03_signup.md
      - PUT - Store Data: 04_homeserver_api/04_put.md
      - GET - Retrieve Data: 04_homeserver_api/05_get.md
      - DELETE - Remove Data: 04_homeserver_api/06_delete.md
  - 3rd Party QR Authorization: 09_qr_auth.md
  - Pubky App:
      - Intro: 02_pubky_app/00_intro.md
  - Build Your Own App:
      - Intro: 03_build_own_app/00_intro.md
