[package]
name = "pubky-snippets"
version = "0.1.0"
edition = "2024"

[dependencies]
# --8<-- [start:pubky-deps]
pubky = { version = "0.6.0-rc.6" }
# --8<-- [end:pubky-deps]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
